import type { ApiEntry } from "./types";

export const aiMlApis: ApiEntry[] = [
  {
    slug: "huggingface-inference-api",
    name: "Hugging Face Inference API",
    description: "Run thousands of open-source ML models via a single hosted API.",
    longDescription:
      "Hugging Face's Inference API lets developers call thousands of community and open-source models (text, vision, audio) without hosting any infrastructure.",
    baseUrl: "https://api-inference.huggingface.co",
    docsUrl: "https://huggingface.co/docs/api-inference/index",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["ai", "machine-learning", "open-source"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "openai-api",
    name: "OpenAI API",
    description: "GPT language models, embeddings, image and speech APIs.",
    longDescription:
      "OpenAI's API provides access to GPT-family language models, DALL·E image generation, Whisper speech-to-text and embeddings for semantic search.",
    baseUrl: "https://api.openai.com/v1",
    docsUrl: "https://platform.openai.com/docs",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["ai", "llm", "generative-ai"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "ollama-local-api",
    name: "Ollama Local API",
    description: "Open-source local runtime API to serve LLMs like Llama and Mistral offline.",
    longDescription:
      "Ollama is an open-source tool that exposes a local REST API for running large language models like Llama 3 and Mistral directly on your own hardware — no cloud key needed.",
    baseUrl: "http://localhost:11434/api",
    docsUrl: "https://github.com/ollama/ollama/blob/main/docs/api.md",
    authType: "No",
    https: false,
    cors: "Yes",
    isTestable: false,
    tags: ["ai", "llm", "self-hosted", "open-source"],
    sourceListUrl: "https://github.com/ollama/ollama",
  },
  {
    slug: "stability-ai-api",
    name: "Stability AI API",
    description: "API for Stable Diffusion image generation models.",
    longDescription:
      "Stability AI's API gives programmatic access to Stable Diffusion image-generation and upscaling models, the leading open-weights image AI family.",
    baseUrl: "https://api.stability.ai/v2beta",
    docsUrl: "https://platform.stability.ai/docs/api-reference",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["ai", "image-generation"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "deepl-api",
    name: "DeepL API",
    description: "High-quality neural machine translation API across 30+ languages.",
    longDescription:
      "DeepL's API is renowned for state-of-the-art neural translation quality, with a free tier covering 500,000 characters per month.",
    baseUrl: "https://api-free.deepl.com/v2",
    docsUrl: "https://developers.deepl.com/docs",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["ai", "translation", "nlp"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "libretranslate",
    name: "LibreTranslate",
    description: "Fully open-source, self-hostable machine translation API.",
    longDescription:
      "LibreTranslate is a free and open-source machine translation API that can be self-hosted with zero telemetry, an ethical alternative to proprietary translation APIs.",
    baseUrl: "https://libretranslate.com",
    docsUrl: "https://github.com/LibreTranslate/LibreTranslate",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["ai", "translation", "open-source", "self-hosted"],
    sourceListUrl: "https://github.com/LibreTranslate/LibreTranslate",
  },
  {
    slug: "deepgram-api",
    name: "Deepgram API",
    description: "Fast, accurate speech-to-text and voice AI API.",
    longDescription:
      "Deepgram provides low-latency automatic speech recognition and voice-agent APIs used widely in call-center and transcription products.",
    baseUrl: "https://api.deepgram.com/v1",
    docsUrl: "https://developers.deepgram.com/docs",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["ai", "speech-to-text"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "google-vision-api",
    name: "Google Cloud Vision API",
    description: "Image analysis API for OCR, labeling, face and object detection.",
    longDescription:
      "Google's Vision API performs OCR, label detection, landmark recognition and explicit-content moderation on images at scale.",
    baseUrl: "https://vision.googleapis.com/v1",
    docsUrl: "https://cloud.google.com/vision/docs",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["ai", "computer-vision"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "replicate-api",
    name: "Replicate API",
    description: "Run open-source ML models in the cloud via a single unified API.",
    longDescription:
      "Replicate lets developers run thousands of open-source machine-learning models (image, video, audio, text) through one consistent API without managing GPUs.",
    baseUrl: "https://api.replicate.com/v1",
    docsUrl: "https://replicate.com/docs/reference/http",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["ai", "open-source", "generative-ai"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "wit-ai",
    name: "Wit.ai (Meta)",
    description: "Free natural-language understanding API for building voice/text bots.",
    longDescription:
      "Meta's Wit.ai is a free natural-language-processing API for extracting intents and entities from text or speech, ideal for chatbot builders.",
    baseUrl: "https://api.wit.ai",
    docsUrl: "https://wit.ai/docs",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["ai", "nlp", "chatbots"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
