import type { ApiEntry } from "./types";

export const animeApis: ApiEntry[] = [
  {
    slug: "jikan",
    name: "Jikan",
    description: "Unofficial MyAnimeList API — anime, manga, characters, seasons and more.",
    longDescription:
      "Jikan is a free, open-source REST API that scrapes and caches MyAnimeList data so developers can query anime, manga, characters, staff, seasonal charts and top rankings without needing an official MAL API key.",
    baseUrl: "https://api.jikan.moe/v4",
    docsUrl: "https://docs.api.jikan.moe/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "manga", "myanimelist", "database"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "anilist",
    name: "AniList GraphQL API",
    description: "GraphQL API for anime and manga metadata, scores, and user lists.",
    longDescription:
      "AniList exposes a powerful GraphQL endpoint covering anime and manga catalogs, staff, studios, airing schedules and community scoring — widely used to power anime tracking apps and Discord bots.",
    baseUrl: "https://graphql.anilist.co",
    docsUrl: "https://docs.anilist.co/",
    authType: "OAuth",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["anime", "manga", "graphql"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "kitsu",
    name: "Kitsu",
    description: "JSON:API for anime and manga tracking, libraries and reviews.",
    longDescription:
      "Kitsu's public JSON:API lets you search anime/manga, fetch episode data, categories and user library entries for building tracker apps.",
    baseUrl: "https://kitsu.io/api/edge",
    docsUrl: "https://kitsu.docs.apiary.io/",
    authType: "OAuth",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "manga", "tracker"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "waifu-pics",
    name: "Waifu.pics",
    description: "SFW & NSFW-tagged anime image API with categorized image pools.",
    longDescription:
      "A simple image API returning random anime-style images by category (e.g. waifu, neko, hug, pat). Endpoints are clearly split into sfw/ and separately gated pools.",
    baseUrl: "https://api.waifu.pics",
    docsUrl: "https://waifu.pics/docs",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["anime", "images", "gif"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "waifu-im",
    name: "Waifu.im",
    description: "Tag-based anime image API with search and image metadata.",
    longDescription:
      "Waifu.im provides a searchable, tag-based anime image database with metadata like dominant color, source and uploader — designed for building image widgets and Discord bots.",
    baseUrl: "https://api.waifu.im",
    docsUrl: "https://docs.waifu.im/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "images"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "animechan",
    name: "AnimeChan",
    description: "Anime quotes API sourced from popular anime and characters.",
    longDescription:
      "AnimeChan returns a huge collection of anime quotes tied to specific characters and anime titles — great for widgets, bots and generators.",
    baseUrl: "https://animechan.io/api/v1",
    docsUrl: "https://animechan.io/docs",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "quotes"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "mangadex",
    name: "MangaDex API",
    description: "Full-featured manga catalog, chapters, covers and reading-progress API.",
    longDescription:
      "MangaDex's public API exposes manga metadata, chapter feeds, scanlation groups and cover art — one of the most complete open manga datasets available.",
    baseUrl: "https://api.mangadex.org",
    docsUrl: "https://api.mangadex.org/docs/",
    authType: "OAuth",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["manga", "comics"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "trace-moe",
    name: "trace.moe",
    description: "Reverse image search engine to find which anime a screenshot is from.",
    longDescription:
      "trace.moe lets you upload or link a screenshot and returns the matching anime, episode and exact timestamp using scene search technology.",
    baseUrl: "https://api.trace.moe",
    docsUrl: "https://soruly.github.io/trace.moe-api/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "reverse-image-search"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "studio-ghibli",
    name: "Studio Ghibli API",
    description: "Films, characters, locations, species and vehicles from Studio Ghibli movies.",
    longDescription:
      "A community-maintained, read-only REST API cataloging every Studio Ghibli film with related characters, locations and species — perfect for practice projects.",
    baseUrl: "https://ghibliapi.vercel.app",
    docsUrl: "https://ghibliapi.vercel.app",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "movies", "studio-ghibli"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "danbooru",
    name: "Danbooru API",
    description: "Large tag-based anime art board API with advanced tag search.",
    longDescription:
      "Danbooru exposes a JSON API for its huge tag-organized anime/manga artwork board, supporting complex boolean tag search queries.",
    baseUrl: "https://danbooru.donmai.us",
    docsUrl: "https://danbooru.donmai.us/wiki_pages/help:api",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["anime", "art", "images"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "nekos-best",
    name: "Nekos.best",
    description: "High-quality categorized anime GIF & image API.",
    longDescription:
      "Nekos.best serves curated, high resolution anime reaction GIFs and images grouped by category such as hug, pat, smile and dance.",
    baseUrl: "https://nekos.best/api/v2",
    docsUrl: "https://docs.nekos.best/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "gif", "images"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "jikan-seasons",
    name: "Jikan Seasonal Charts",
    description: "Seasonal anime charts endpoint (winter/spring/summer/fall) via Jikan.",
    longDescription:
      "A specialised slice of the Jikan API returning the current or historical seasonal anime charts, useful for release calendars.",
    baseUrl: "https://api.jikan.moe/v4/seasons",
    docsUrl: "https://docs.api.jikan.moe/#tag/seasons",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "seasonal", "calendar"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "otakugifs",
    name: "otakugifs.xyz",
    description: "Simple reaction GIF API themed around anime emotions.",
    longDescription:
      "A lightweight endpoint returning random anime reaction GIFs by emotion tag (blush, cry, dance, laugh) — ideal for chat bots.",
    baseUrl: "https://api.otakugifs.xyz",
    docsUrl: "https://otakugifs.xyz/api/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "gif"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "anime-facts-rest-api",
    name: "Anime Facts REST API",
    description: "Random curated anime trivia and facts endpoint.",
    longDescription:
      "Returns random, curated fun-facts about anime and the industry, great for trivia widgets and Discord bots.",
    baseUrl: "https://anime-facts-rest-api.herokuapp.com/api/v1",
    docsUrl: "https://github.com/chandan-jaiswal/anime-facts-rest-api",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "trivia"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "shikimori",
    name: "Shikimori API",
    description: "Russian anime/manga community platform API with rich catalog data.",
    longDescription:
      "Shikimori exposes anime, manga, character, and user-list endpoints from one of the largest Russian-language anime community platforms.",
    baseUrl: "https://shikimori.one/api",
    docsUrl: "https://shikimori.one/api/doc",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["anime", "manga", "community"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "animeflv-unofficial",
    name: "AnimeFLV Unofficial API",
    description: "Community wrapper exposing AnimeFLV catalog & episode listings.",
    longDescription:
      "An open-source unofficial wrapper that structures AnimeFLV's public catalog pages into a clean JSON API for Spanish-language anime data.",
    baseUrl: "https://api-animeflv.herokuapp.com",
    docsUrl: "https://github.com/KuroiAkano/animeflv-api",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["anime", "streaming-metadata"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "myanimelist-official",
    name: "MyAnimeList Official API v2",
    description: "Official OAuth2 API for MyAnimeList user lists and catalog search.",
    longDescription:
      "MAL's first-party API (OAuth2) enables catalog search plus authenticated read/write access to a user's anime and manga list.",
    baseUrl: "https://api.myanimelist.net/v2",
    docsUrl: "https://myanimelist.net/apiconfig/references/api/v2",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["anime", "manga", "official"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "anime-quotes-api-io",
    name: "Animechan.vercel",
    description: "Serverless-hosted mirror of the AnimeChan quotes dataset.",
    longDescription:
      "A Vercel-hosted mirror providing the same character-tagged anime quote dataset with fast edge response times.",
    baseUrl: "https://animechan.vercel.app/api",
    docsUrl: "https://github.com/RocktimSaikia/anime-chan",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["anime", "quotes"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "consumet",
    name: "Consumet API",
    description: "Open-source aggregator API for anime, manga and light-novel streaming metadata.",
    longDescription:
      "Consumet is a popular open-source project providing unified endpoints across multiple anime/manga source sites for metadata and episode links (self-hostable).",
    baseUrl: "https://api.consumet.org",
    docsUrl: "https://docs.consumet.org/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["anime", "manga", "self-hosted", "aggregator"],
    sourceListUrl: "https://github.com/consumet/consumet.ts",
  },
  {
    slug: "anilist-trending",
    name: "AniList Trending (GraphQL query)",
    description: "Popular AniList GraphQL query pattern for trending anime this week.",
    longDescription:
      "A widely-used GraphQL query preset against the AniList API to retrieve currently trending anime titles, scores and cover art.",
    baseUrl: "https://graphql.anilist.co",
    docsUrl: "https://anilist.gitbook.io/anilist-apiv2-docs/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["anime", "trending", "graphql"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
