import type { ApiEntry } from "./types";

export const financeApis: ApiEntry[] = [
  {
    slug: "coingecko",
    name: "CoinGecko API",
    description: "Free, no-key cryptocurrency market data API covering 10,000+ coins.",
    longDescription:
      "CoinGecko's public API delivers real-time and historical price, market cap, and volume data for the world's largest catalog of cryptocurrencies, entirely free without a key on the public tier.",
    baseUrl: "https://api.coingecko.com/api/v3",
    docsUrl: "https://www.coingecko.com/en/api/documentation",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["finance", "crypto"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "coinbase-api",
    name: "Coinbase API",
    description: "Official Coinbase exchange API for prices, accounts and trading.",
    longDescription:
      "Coinbase's official API exposes live spot/buy/sell prices plus authenticated trading and account endpoints for the popular crypto exchange.",
    baseUrl: "https://api.coinbase.com/v2",
    docsUrl: "https://docs.cdp.coinbase.com/",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["finance", "crypto", "exchange"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "exchangerate-api",
    name: "ExchangeRate-API",
    description: "Free currency conversion & exchange-rate API for 160+ currencies.",
    longDescription:
      "ExchangeRate-API offers a generous free tier for real-time and historical foreign-exchange rates across 160+ world currencies.",
    baseUrl: "https://open.er-api.com/v6",
    docsUrl: "https://www.exchangerate-api.com/docs/overview",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["finance", "forex", "currency"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "frankfurter",
    name: "Frankfurter API",
    description: "Free, open-source exchange rate API using European Central Bank data.",
    longDescription:
      "Frankfurter is a fully open-source foreign exchange API built on official European Central Bank reference rates, with no API key required.",
    baseUrl: "https://api.frankfurter.dev/v1",
    docsUrl: "https://frankfurter.dev/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["finance", "forex", "open-source"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "alphavantage",
    name: "Alpha Vantage",
    description: "Free stock, forex and crypto market data API with technical indicators.",
    longDescription:
      "Alpha Vantage offers a free-tier API covering real-time and historical stock quotes, forex rates, crypto prices and 50+ technical indicators.",
    baseUrl: "https://www.alphavantage.co/query",
    docsUrl: "https://www.alphavantage.co/documentation/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["finance", "stocks"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "iex-cloud",
    name: "IEX Cloud",
    description: "Real-time and historical US stock market data platform.",
    longDescription:
      "IEX Cloud provides reliable real-time and historical equity market data used by fintech startups, with transparent usage-based pricing.",
    baseUrl: "https://cloud.iexapis.com/stable",
    docsUrl: "https://iexcloud.io/docs/api/",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["finance", "stocks"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "worldbank-data",
    name: "World Bank Open Data API",
    description: "Free global economic & development indicators API.",
    longDescription:
      "The World Bank's open API provides decades of free economic, demographic and development indicators for every country on Earth.",
    baseUrl: "https://api.worldbank.org/v2",
    docsUrl: "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["finance", "economics", "open-data"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "plaid-api",
    name: "Plaid API",
    description: "Bank-account linking API used by thousands of fintech apps.",
    longDescription:
      "Plaid's API connects apps to users' bank accounts for balance checks, transaction history and identity verification, powering most modern fintech products.",
    baseUrl: "https://production.plaid.com",
    docsUrl: "https://plaid.com/docs/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["finance", "banking"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "binance-api",
    name: "Binance Public API",
    description: "Free public market-data API from the world's largest crypto exchange.",
    longDescription:
      "Binance's public REST & WebSocket API provides free real-time order books, candlesticks and trade data without authentication for market data endpoints.",
    baseUrl: "https://api.binance.com",
    docsUrl: "https://developers.binance.com/docs/binance-spot-api-docs",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["finance", "crypto", "exchange"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "frankfurter-historical",
    name: "Open Exchange Rates",
    description: "Simple, reliable exchange-rate API with a free hobbyist tier.",
    longDescription:
      "Open Exchange Rates provides a straightforward JSON API for current and historical currency exchange rates trusted by developers worldwide.",
    baseUrl: "https://openexchangerates.org/api",
    docsUrl: "https://docs.openexchangerates.org/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["finance", "forex"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
