import type { ApiEntry } from "./types";

export const gamingApis: ApiEntry[] = [
  {
    slug: "pokeapi",
    name: "PokéAPI",
    description: "The complete Pokémon data API — species, moves, abilities, types and sprites.",
    longDescription:
      "PokéAPI is a fully free, RESTful, community-run API exposing deep Pokémon data including species evolution chains, moves, items, abilities and official artwork.",
    baseUrl: "https://pokeapi.co/api/v2",
    docsUrl: "https://pokeapi.co/docs/v2",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["gaming", "pokemon"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "steam-web-api",
    name: "Steam Web API",
    description: "Official Valve API for player stats, game details, achievements and store data.",
    longDescription:
      "Valve's official Web API exposes player-owned games, achievements, friend lists and the full app catalog data used by the Steam store and community.",
    baseUrl: "https://api.steampowered.com",
    docsUrl: "https://steamcommunity.com/dev",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["gaming", "steam"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "riot-games-api",
    name: "Riot Games API",
    description: "Official API for League of Legends, VALORANT and TFT match & rank data.",
    longDescription:
      "Riot's developer portal gives authenticated access to match histories, ranked ladders, champion mastery and esports data across their game titles.",
    baseUrl: "https://developer.riotgames.com",
    docsUrl: "https://developer.riotgames.com/apis",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["gaming", "esports", "league-of-legends", "valorant"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "chess-com-api",
    name: "Chess.com Published Data API",
    description: "Public read-only API for Chess.com player profiles, stats and game archives.",
    longDescription:
      "Chess.com's Published-Data API exposes player profiles, ratings, titled-player lists, clubs and monthly game archives with zero authentication required.",
    baseUrl: "https://api.chess.com/pub",
    docsUrl: "https://www.chess.com/news/view/published-data-api",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["gaming", "chess"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "lichess-api",
    name: "Lichess API",
    description: "Fully open-source chess platform API — games, puzzles, broadcasts and bots.",
    longDescription:
      "Lichess exposes an extensive open API for game exports, puzzle databases, tournament data and even Board/Bot APIs to play programmatically.",
    baseUrl: "https://lichess.org/api",
    docsUrl: "https://lichess.org/api",
    authType: "OAuth",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["gaming", "chess", "open-source"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "rawg",
    name: "RAWG Video Games Database",
    description: "One of the largest video game databases with 500,000+ titles.",
    longDescription:
      "RAWG offers metadata for hundreds of thousands of games across all platforms — ratings info, screenshots, genres, developers and release dates.",
    baseUrl: "https://api.rawg.io/api",
    docsUrl: "https://api.rawg.io/docs/",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["gaming", "database"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "igdb",
    name: "IGDB API",
    description: "Twitch-owned Internet Game Database — deep metadata on games and companies.",
    longDescription:
      "IGDB, backed by Twitch, provides one of the richest structured video-game metadata sets covering franchises, companies, platforms and release info.",
    baseUrl: "https://api.igdb.com/v4",
    docsUrl: "https://api-docs.igdb.com/",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["gaming", "database"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "freetogame",
    name: "FreeToGame API",
    description: "Catalog of free-to-play PC and browser games with filters by genre/platform.",
    longDescription:
      "FreeToGame's public API lists hundreds of free-to-play titles with genre, platform and publisher filters — no key required.",
    baseUrl: "https://www.freetogame.com/api",
    docsUrl: "https://www.freetogame.com/api-doc",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["gaming", "free-to-play"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "guerrilla-games-jsonplaceholder",
    name: "Open Trivia Database",
    description: "Free trivia question API with categories, difficulty tiers and types.",
    longDescription:
      "The Open Trivia Database (OpenTDB) offers a huge community-verified set of trivia questions, ideal for building quiz games.",
    baseUrl: "https://opentdb.com/api.php",
    docsUrl: "https://opentdb.com/api_config.php",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["gaming", "trivia", "quiz"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "hltb",
    name: "HowLongToBeat (unofficial)",
    description: "Community wrapper for HowLongToBeat completion-time data.",
    longDescription:
      "An open-source wrapper structuring HowLongToBeat's game completion-time statistics (main story, completionist, etc.) into a JSON API.",
    baseUrl: "https://howlongtobeat.com/api",
    docsUrl: "https://github.com/ckatzorke/howlongtobeat",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["gaming", "completion-time"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "deck-of-cards",
    name: "Deck of Cards API",
    description: "Simulate real playing-card decks: shuffle, draw and pile management.",
    longDescription:
      "A fun, free API that simulates one or more standard 52-card decks with shuffle/draw/pile endpoints for building card games.",
    baseUrl: "https://deckofcardsapi.com/api/deck",
    docsUrl: "https://deckofcardsapi.com/",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["gaming", "cards"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "battlenet-api",
    name: "Battle.net API",
    description: "Blizzard's official API for WoW, Overwatch, Diablo and Hearthstone data.",
    longDescription:
      "Blizzard's official developer portal exposes game data and community APIs for World of Warcraft, Diablo III, Overwatch and Hearthstone.",
    baseUrl: "https://develop.battle.net",
    docsUrl: "https://develop.battle.net/documentation",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["gaming", "blizzard"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "brawlstars-api",
    name: "Brawl Stars API",
    description: "Official Supercell API for Brawl Stars player/battle/club data.",
    longDescription:
      "Supercell's official Brawl Stars API returns player profiles, brawler stats, club rosters and battle logs.",
    baseUrl: "https://api.brawlstars.com/v1",
    docsUrl: "https://developer.brawlstars.com/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["gaming", "supercell"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "clash-of-clans-api",
    name: "Clash of Clans API",
    description: "Official Supercell API for clans, players, wars and leaderboards.",
    longDescription:
      "Supercell's official Clash of Clans API returns clan info, player profiles, current war status and global leaderboards.",
    baseUrl: "https://api.clashofclans.com/v1",
    docsUrl: "https://developer.clashofclans.com/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["gaming", "supercell"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "guildwars2-api",
    name: "Guild Wars 2 API",
    description: "Official ArenaNet API for account, items, achievements and world data.",
    longDescription:
      "ArenaNet's official Guild Wars 2 API is one of the most complete MMO data APIs, exposing items, crafting recipes, world bosses, and account data.",
    baseUrl: "https://api.guildwars2.com/v2",
    docsUrl: "https://wiki.guildwars2.com/wiki/API:Main",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["gaming", "mmo"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "osu-api",
    name: "osu! API",
    description: "Official osu! rhythm game API for beatmaps, scores and user stats.",
    longDescription:
      "osu!'s official API (v2, OAuth2) exposes beatmap sets, user statistics, rankings and score data for the popular rhythm game.",
    baseUrl: "https://osu.ppy.sh/api/v2",
    docsUrl: "https://osu.ppy.sh/docs/index.html",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["gaming", "rhythm-game"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "giant-bomb-api",
    name: "Giant Bomb API",
    description: "Massive wiki-style video game database with reviews-info and franchises.",
    longDescription:
      "Giant Bomb's API is backed by one of the internet's largest crowd-sourced video game wikis, covering franchises, characters, and platforms.",
    baseUrl: "https://www.giantbomb.com/api",
    docsUrl: "https://www.giantbomb.com/api/documentation",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["gaming", "database", "wiki"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "minecraft-api",
    name: "Minecraft Services API",
    description: "Official Mojang API for profile lookups, skins, and server status.",
    longDescription:
      "Mojang's official API endpoints let developers resolve Minecraft usernames to UUIDs, fetch skins/capes and check account/server status.",
    baseUrl: "https://api.mojang.com",
    docsUrl: "https://minecraft.wiki/w/Mojang_API",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["gaming", "minecraft"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "fortnite-api",
    name: "Fortnite-API.com",
    description: "Community-run API for Fortnite cosmetics, shop rotation and stats.",
    longDescription:
      "An open, well-maintained community API returning Fortnite cosmetic catalogs, the daily item shop, playlists and news feeds.",
    baseUrl: "https://fortnite-api.com/v2",
    docsUrl: "https://dash.fortnite-api.com/",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["gaming", "fortnite"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "speedrun-com-api",
    name: "Speedrun.com API",
    description: "Official REST API for speedrunning leaderboards across thousands of games.",
    longDescription:
      "speedrun.com's public REST API exposes game categories, runs, leaderboards and runner profiles for the world's speedrunning community.",
    baseUrl: "https://www.speedrun.com/api/v1",
    docsUrl: "https://github.com/speedruncomorg/api",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["gaming", "speedrunning"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
