import type { ApiEntry } from "./types";

export const moviesTvApis: ApiEntry[] = [
  {
    slug: "tmdb",
    name: "The Movie Database (TMDB)",
    description: "Community-driven movie and TV metadata API with huge coverage and images.",
    longDescription:
      "TMDB's API is one of the most widely used movie/TV datasets, offering cast, crew, images, trailers and localized metadata for millions of titles.",
    baseUrl: "https://api.themoviedb.org/3",
    docsUrl: "https://developer.themoviedb.org/docs",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["movies", "tv", "metadata"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "omdb",
    name: "OMDb API",
    description: "Open Movie Database — plot, cast, ratings-info and posters via IMDb IDs.",
    longDescription:
      "OMDb exposes IMDb-sourced structured movie and series data including plots, cast, posters and box-office info via a simple REST endpoint.",
    baseUrl: "https://www.omdbapi.com",
    docsUrl: "https://www.omdbapi.com/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["movies", "imdb"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "tvmaze",
    name: "TVmaze API",
    description: "Free TV show database — episodes, cast, schedules and streaming info.",
    longDescription:
      "TVmaze offers a completely free, no-auth API for TV show information, full episode lists, cast data and daily air schedules by country.",
    baseUrl: "https://api.tvmaze.com",
    docsUrl: "https://www.tvmaze.com/api",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["tv", "schedules"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "studio-ghibli-films",
    name: "Studio Ghibli Films API",
    description: "Simple REST API listing every Studio Ghibli film with metadata.",
    longDescription:
      "A lightweight, free API returning structured data about every Studio Ghibli film release, running time and description.",
    baseUrl: "https://ghibliapi.vercel.app/films",
    docsUrl: "https://ghibliapi.vercel.app",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["movies", "animation"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "star-wars-swapi",
    name: "SWAPI (Star Wars API)",
    description: "The classic open API for Star Wars films, characters, ships and planets.",
    longDescription:
      "SWAPI is one of the most iconic learn-to-code demo APIs, returning structured data on Star Wars films, people, planets, starships and species.",
    baseUrl: "https://swapi.dev/api",
    docsUrl: "https://swapi.dev/documentation",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["movies", "star-wars"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "trakt",
    name: "Trakt API",
    description: "Movie & TV tracking API with watch history, ratings-info and recommendations.",
    longDescription:
      "Trakt's developer API powers watch-history tracking apps with comprehensive movie/TV metadata, scrobbling, lists and personalized recommendations.",
    baseUrl: "https://api.trakt.tv",
    docsUrl: "https://trakt.docs.apiary.io/",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["movies", "tv", "tracker"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "justwatch-unofficial",
    name: "JustWatch (unofficial)",
    description: "Community wrapper exposing JustWatch's streaming-availability data.",
    longDescription:
      "An open-source unofficial client that queries JustWatch's public endpoints to show which streaming platforms carry a given title by region.",
    baseUrl: "https://apis.justwatch.com",
    docsUrl: "https://github.com/dawoudt/JustWatchAPI",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["movies", "tv", "streaming"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "rotten-tomatoes-unofficial",
    name: "Rotten Tomatoes (unofficial data)",
    description: "Community-maintained dataset mirrors of Rotten Tomatoes scoring info.",
    longDescription:
      "Since Rotten Tomatoes retired its public API, several open datasets and scraping toolkits mirror score/critic data for research and hobby projects.",
    baseUrl: "https://www.rottentomatoes.com",
    docsUrl: "https://github.com/topics/rotten-tomatoes-scraper",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["movies", "reviews-info"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "watchmode",
    name: "Watchmode API",
    description: "Streaming availability API across 200+ platforms worldwide.",
    longDescription:
      "Watchmode aggregates where movies/shows are streaming (subscription, rent, buy) across hundreds of platforms and regions.",
    baseUrl: "https://api.watchmode.com/v1",
    docsUrl: "https://api.watchmode.com/",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["movies", "tv", "streaming"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "the-omdb-search",
    name: "OMDb Search Endpoint",
    description: "Fuzzy title-search slice of OMDb for building autocomplete UIs.",
    longDescription:
      "A dedicated search endpoint on OMDb for fuzzy matching movie/show titles, useful for search-as-you-type UI components.",
    baseUrl: "https://www.omdbapi.com/?s=",
    docsUrl: "https://www.omdbapi.com/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["movies", "search"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "tmdb-trending",
    name: "TMDB Trending Endpoint",
    description: "Daily/weekly trending movies & TV slice of the TMDB API.",
    longDescription:
      "A dedicated TMDB endpoint returning what's trending today or this week across movies, TV and people globally.",
    baseUrl: "https://api.themoviedb.org/3/trending",
    docsUrl: "https://developer.themoviedb.org/reference/trending-all",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["movies", "trending"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "letterboxd-unofficial",
    name: "Letterboxd (unofficial)",
    description: "Community wrappers for Letterboxd public diary and list pages.",
    longDescription:
      "While Letterboxd's official API is invite-only, several open-source scraping libraries structure its public diary, watchlist and list pages into JSON.",
    baseUrl: "https://letterboxd.com",
    docsUrl: "https://github.com/topics/letterboxd-api",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["movies", "reviews-info", "community"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
