import type { ApiEntry } from "./types";

export const musicApis: ApiEntry[] = [
  {
    slug: "spotify-web-api",
    name: "Spotify Web API",
    description: "Official Spotify API for tracks, playlists, artists and playback control.",
    longDescription:
      "Spotify's official Web API exposes catalog search, audio features, playlists and playback control for the world's largest music streaming platform.",
    baseUrl: "https://api.spotify.com/v1",
    docsUrl: "https://developer.spotify.com/documentation/web-api",
    authType: "OAuth",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["music", "streaming"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "musicbrainz",
    name: "MusicBrainz API",
    description: "Open-source, community-maintained music metadata encyclopedia.",
    longDescription:
      "MusicBrainz is a completely open, non-profit music metadata database offering release, artist and recording data under a permissive license.",
    baseUrl: "https://musicbrainz.org/ws/2",
    docsUrl: "https://musicbrainz.org/doc/MusicBrainz_API",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["music", "open-source", "metadata"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "lyrics-ovh",
    name: "Lyrics.ovh",
    description: "Free, simple API to fetch song lyrics by artist and title.",
    longDescription:
      "Lyrics.ovh is a free, open API that returns full song lyrics given an artist and track title — no key required.",
    baseUrl: "https://api.lyrics.ovh/v1",
    docsUrl: "https://lyricsovh.docs.apiary.io/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["music", "lyrics"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "deezer-api",
    name: "Deezer API",
    description: "Free public API for Deezer's music catalog, charts and playlists.",
    longDescription:
      "Deezer's API offers open, no-auth catalog browsing including top charts, artist discographies, and 30-second track previews.",
    baseUrl: "https://api.deezer.com",
    docsUrl: "https://developers.deezer.com/api",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["music", "streaming"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "genius-api",
    name: "Genius API",
    description: "Official Genius API for lyrics annotations, song and artist metadata.",
    longDescription:
      "Genius's API exposes song metadata, artist info and community annotations that explain lyric meaning and cultural references.",
    baseUrl: "https://api.genius.com",
    docsUrl: "https://docs.genius.com/",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["music", "lyrics"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "last-fm-api",
    name: "Last.fm API",
    description: "Music scrobbling and recommendation API with rich listening-history data.",
    longDescription:
      "Last.fm's API exposes scrobbles, top artists/tracks, similar-artist recommendations and tag clouds from one of the oldest music-tracking communities.",
    baseUrl: "https://ws.audioscrobbler.com/2.0",
    docsUrl: "https://www.last.fm/api",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["music", "recommendations"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "itunes-search-api",
    name: "iTunes Search API",
    description: "Apple's free public API for searching music, podcasts and media metadata.",
    longDescription:
      "Apple's iTunes Search API lets developers search the entire iTunes Store catalog (songs, albums, podcasts, movies) with zero authentication.",
    baseUrl: "https://itunes.apple.com/search",
    docsUrl: "https://performance-partners.apple.com/search-api",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["music", "podcasts", "apple"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "audiodb",
    name: "TheAudioDB",
    description: "Free community-driven music metadata & artwork database.",
    longDescription:
      "TheAudioDB offers free-tier access to artist biographies, album art, band logos and track listings contributed by the community.",
    baseUrl: "https://www.theaudiodb.com/api/v1/json",
    docsUrl: "https://www.theaudiodb.com/api_guide.php",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["music", "metadata"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "soundcloud-api",
    name: "SoundCloud API",
    description: "Official API for streaming, uploading and searching SoundCloud tracks.",
    longDescription:
      "SoundCloud's developer API allows track search, streaming URLs and playlist management for the popular independent-artist audio platform.",
    baseUrl: "https://api.soundcloud.com",
    docsUrl: "https://developers.soundcloud.com/docs/api/guide",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["music", "streaming"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "bandsintown-api",
    name: "Bandsintown API",
    description: "Live concert and tour-date API for artists worldwide.",
    longDescription:
      "Bandsintown's API returns upcoming concert dates, venues and ticket links for artists, powering countless gig-discovery apps.",
    baseUrl: "https://rest.bandsintown.com",
    docsUrl: "https://www.artists.bandsintown.com/support/api-installation",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["music", "concerts", "events"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
