import type { ApiEntry } from "./types";

export const newsMediaApis: ApiEntry[] = [
  {
    slug: "newsapi-org",
    name: "NewsAPI.org",
    description: "Headlines and articles aggregated from 80,000+ global news sources.",
    longDescription:
      "NewsAPI.org indexes headlines and full articles from tens of thousands of publishers worldwide, searchable by keyword, language, source and date.",
    baseUrl: "https://newsapi.org/v2",
    docsUrl: "https://newsapi.org/docs",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["news", "media"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "gnews-api",
    name: "GNews API",
    description: "Free-tier news search API with real-time headlines by topic and country.",
    longDescription:
      "GNews indexes news articles from thousands of sources, offering a free tier for real-time headline search filtered by country, language and topic.",
    baseUrl: "https://gnews.io/api/v4",
    docsUrl: "https://gnews.io/docs/v4",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["news"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "reddit-api",
    name: "Reddit API",
    description: "Official API for subreddit posts, comments and trending discussions.",
    longDescription:
      "Reddit's official API exposes subreddit listings, post threads and comment trees, powering countless bots, aggregators and research tools.",
    baseUrl: "https://oauth.reddit.com",
    docsUrl: "https://www.reddit.com/dev/api/",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["news", "social", "community"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "wikipedia-api",
    name: "Wikipedia REST API",
    description: "Official Wikimedia API for article summaries, search and page content.",
    longDescription:
      "The Wikimedia REST API returns article summaries, full page HTML, page-view analytics and search results across every language edition of Wikipedia.",
    baseUrl: "https://en.wikipedia.org/api/rest_v1",
    docsUrl: "https://www.mediawiki.org/wiki/API:REST_API",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["news", "encyclopedia", "open-data"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "nytimes-api",
    name: "New York Times API",
    description: "Official NYT API for articles, best-seller lists and archive search.",
    longDescription:
      "The New York Times Developer Network offers free-tier APIs for article search, top stories, book best-seller lists and the full historical archive.",
    baseUrl: "https://api.nytimes.com/svc",
    docsUrl: "https://developer.nytimes.com/apis",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["news", "journalism"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "guardian-api",
    name: "The Guardian Open Platform",
    description: "Free official API exposing The Guardian's full article archive.",
    longDescription:
      "The Guardian's Open Platform grants free access to over 2 million articles dating back to 1999, including tags, sections and multimedia.",
    baseUrl: "https://content.guardianapis.com",
    docsUrl: "https://open-platform.theguardian.com/documentation/",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["news", "journalism", "open-data"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "mediastack",
    name: "Mediastack API",
    description: "Real-time and historical worldwide news-data API.",
    longDescription:
      "Mediastack aggregates live and historical news data from thousands of sources across 50+ countries with a free-tier plan.",
    baseUrl: "https://api.mediastack.com/v1",
    docsUrl: "https://mediastack.com/documentation",
    authType: "apiKey",
    https: false,
    cors: "Unknown",
    isTestable: false,
    tags: ["news"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "hackernews-algolia",
    name: "HN Algolia Search API",
    description: "Fast full-text search API over the entire Hacker News archive.",
    longDescription:
      "Backed by Algolia, this free API provides lightning-fast full-text search across every Hacker News story and comment ever posted.",
    baseUrl: "https://hn.algolia.com/api/v1",
    docsUrl: "https://hn.algolia.com/api",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["news", "tech", "search"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
