import type { ApiEntry } from "./types";

export const scienceSpaceApis: ApiEntry[] = [
  {
    slug: "nasa-open-apis",
    name: "NASA Open APIs",
    description: "Official NASA API hub — APOD, Mars rover photos, near-earth objects and more.",
    longDescription:
      "NASA's open API portal offers the beloved Astronomy Picture of the Day, Mars Rover photo archives, near-Earth-object tracking, and Earth satellite imagery, all free with a shared demo key.",
    baseUrl: "https://api.nasa.gov",
    docsUrl: "https://api.nasa.gov/",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["science", "space", "nasa"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "spacex-api",
    name: "SpaceX API (open-source)",
    description: "Community-maintained open-source API for SpaceX launches, rockets & crew.",
    longDescription:
      "The open-source r-spacex API tracks every SpaceX launch, rocket, capsule, landing pad and crew member with a completely free, no-key REST interface.",
    baseUrl: "https://api.spacexdata.com/v5",
    docsUrl: "https://github.com/r-spacex/SpaceX-API",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["space", "spacex", "open-source"],
    sourceListUrl: "https://github.com/r-spacex/SpaceX-API",
  },
  {
    slug: "open-notify",
    name: "Open Notify",
    description: "Live ISS location and astronauts-in-space API.",
    longDescription:
      "Open Notify is a free, simple API returning the International Space Station's current location and the list of humans currently in space.",
    baseUrl: "http://api.open-notify.org",
    docsUrl: "http://open-notify.org/Open-Notify-API/",
    authType: "No",
    https: false,
    cors: "Yes",
    isTestable: true,
    tags: ["space", "iss"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "usgs-earthquake",
    name: "USGS Earthquake API",
    description: "Official real-time earthquake data feed from the US Geological Survey.",
    longDescription:
      "The USGS Earthquake Hazards Program publishes real-time, free GeoJSON feeds of global earthquakes by magnitude and time window.",
    baseUrl: "https://earthquake.usgs.gov/earthquakes/feed/v1.0",
    docsUrl: "https://earthquake.usgs.gov/fdsnws/event/1/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["science", "earthquakes", "geology"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "nasa-exoplanet-archive",
    name: "NASA Exoplanet Archive API",
    description: "Official catalog of confirmed exoplanets and their properties.",
    longDescription:
      "NASA's Exoplanet Archive TAP API exposes confirmed exoplanet discoveries, host stars and orbital parameters for astrophysics research and apps.",
    baseUrl: "https://exoplanetarchive.ipac.caltech.edu/TAP",
    docsUrl: "https://exoplanetarchive.ipac.caltech.edu/docs/TAP/usingTAP.html",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["science", "space", "astronomy"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "cern-open-data",
    name: "CERN Open Data Portal",
    description: "Real particle-physics datasets from the Large Hadron Collider.",
    longDescription:
      "CERN's Open Data Portal shares real collision datasets, software and analysis tools from the LHC experiments for public research and education.",
    baseUrl: "https://opendata.cern.ch",
    docsUrl: "https://opendata.cern.ch/docs/about-cern-open-data-portal",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["science", "physics", "open-data"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "noaa-api",
    name: "NOAA Climate Data API",
    description: "Official US climate & weather historical dataset API.",
    longDescription:
      "NOAA's National Centers for Environmental Information API exposes decades of historical weather, ocean and climate station data for free.",
    baseUrl: "https://www.ncei.noaa.gov/cdo-web/api/v2",
    docsUrl: "https://www.ncei.noaa.gov/cdo-web/webservices/v2",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["science", "climate", "weather"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "pubchem-api",
    name: "PubChem PUG REST API",
    description: "Free API for chemical compound structures, properties and bioactivity.",
    longDescription:
      "The NIH's PubChem database exposes chemical structures, molecular properties and bioassay data through a free public REST interface.",
    baseUrl: "https://pubchem.ncbi.nlm.nih.gov/rest/pug",
    docsUrl: "https://pubchemdocs.ncbi.nlm.nih.gov/pug-rest",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["science", "chemistry"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "arxiv-api",
    name: "arXiv API",
    description: "Open API for searching millions of scientific preprints.",
    longDescription:
      "arXiv's official API allows programmatic search and metadata retrieval across millions of physics, math, CS and biology research preprints.",
    baseUrl: "https://export.arxiv.org/api",
    docsUrl: "https://info.arxiv.org/help/api/index.html",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["science", "research", "open-access"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
