import type { ApiEntry } from "./types";

export const sportsApis: ApiEntry[] = [
  {
    slug: "thesportsdb",
    name: "TheSportsDB",
    description: "Free, community-driven sports database covering leagues worldwide.",
    longDescription:
      "TheSportsDB provides free access to team badges, league tables, fixtures and player data across football, basketball, cricket and dozens of other sports.",
    baseUrl: "https://www.thesportsdb.com/api/v1/json",
    docsUrl: "https://www.thesportsdb.com/api.php",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["sports", "football", "database"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "football-data-org",
    name: "football-data.org",
    description: "Free tier football API with fixtures, standings and scorers across top leagues.",
    longDescription:
      "football-data.org offers a generous free tier covering competitions like the Premier League, La Liga and Champions League with live scores and standings.",
    baseUrl: "https://api.football-data.org/v4",
    docsUrl: "https://www.football-data.org/documentation/quickstart",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["sports", "football", "soccer"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "balldontlie",
    name: "balldontlie NBA API",
    description: "Free NBA stats API — players, teams, games and season averages.",
    longDescription:
      "balldontlie is a free, no-auth-required NBA data API used widely in tutorials, covering historical and current player/team stats.",
    baseUrl: "https://api.balldontlie.io/v1",
    docsUrl: "https://docs.balldontlie.io/",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["sports", "basketball", "nba"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "cricapi",
    name: "CricAPI",
    description: "Live cricket scores, fixtures and player stats API.",
    longDescription:
      "CricAPI serves live scores, match fixtures, series info and player statistics across international and domestic cricket.",
    baseUrl: "https://api.cricapi.com/v1",
    docsUrl: "https://cricapi.com/docs/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["sports", "cricket"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "api-nba",
    name: "API-NBA",
    description: "Structured NBA data across seasons, standings, players and live games.",
    longDescription:
      "API-NBA (via API-Sports) offers deep historical and live NBA data including box scores, standings and player statistics with a free tier.",
    baseUrl: "https://api-nba-v1.p.rapidapi.com",
    docsUrl: "https://rapidapi.com/api-sports/api/api-nba",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["sports", "basketball"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "openligadb",
    name: "OpenLigaDB",
    description: "Free & open German football league data API (Bundesliga & more).",
    longDescription:
      "OpenLigaDB is a completely free, open-source German sports data project delivering Bundesliga fixtures, results and tables with no key needed.",
    baseUrl: "https://api.openligadb.de",
    docsUrl: "https://www.openligadb.de/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["sports", "football", "bundesliga"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "nhl-api",
    name: "NHL Stats API",
    description: "Unofficial but stable NHL API covering schedules, rosters and live stats.",
    longDescription:
      "Widely used by the hockey developer community, this API mirrors the NHL's own data feeds for schedules, standings and play-by-play stats.",
    baseUrl: "https://statsapi.web.nhl.com/api/v1",
    docsUrl: "https://github.com/dword4/nhlapi",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["sports", "hockey", "nhl"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "mlb-stats-api",
    name: "MLB Stats API",
    description: "Free public MLB data feeds for schedules, box scores and standings.",
    longDescription:
      "MLB's publicly accessible statsapi feeds power countless baseball apps with live scores, historical box scores and player stats.",
    baseUrl: "https://statsapi.mlb.com/api/v1",
    docsUrl: "https://github.com/toddrob99/MLB-StatsAPI",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["sports", "baseball", "mlb"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "ergast-f1",
    name: "Ergast / Jolpica F1 API",
    description: "Historical & live Formula 1 race data — drivers, constructors, results.",
    longDescription:
      "The Ergast API (now continued by the Jolpica community fork) offers complete Formula 1 historical data back to 1950, including lap times and qualifying.",
    baseUrl: "https://api.jolpi.ca/ergast/f1",
    docsUrl: "https://github.com/jolpica/jolpica-f1",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["sports", "formula1", "motorsport"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "api-football",
    name: "API-Football (API-Sports)",
    description: "Comprehensive football data covering 1,100+ leagues worldwide.",
    longDescription:
      "API-Football offers fixtures, live odds, standings, lineups, and player statistics across over a thousand football leagues and cups globally.",
    baseUrl: "https://v3.football.api-sports.io",
    docsUrl: "https://www.api-football.com/documentation-v3",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["sports", "football"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "sportradar",
    name: "Sportradar Developer APIs",
    description: "Professional-grade sports data feeds across 20+ sports globally.",
    longDescription:
      "Sportradar provides official real-time and historical data feeds used by major broadcasters and betting platforms across dozens of sports.",
    baseUrl: "https://developer.sportradar.com",
    docsUrl: "https://developer.sportradar.com/docs",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["sports", "enterprise"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "worldathletics-unofficial",
    name: "World Athletics (open data mirrors)",
    description: "Community mirrors exposing athletics records and rankings data.",
    longDescription:
      "Several open-source projects mirror World Athletics' public rankings and record pages into structured JSON for track & field applications.",
    baseUrl: "https://worldathletics.org",
    docsUrl: "https://github.com/topics/world-athletics",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["sports", "athletics"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
