import type { ApiEntry } from "./types";

export const technologyApis: ApiEntry[] = [
  {
    slug: "github-rest-api",
    name: "GitHub REST API",
    description: "Official GitHub API for repos, users, issues, actions and organizations.",
    longDescription:
      "GitHub's REST API v3 is the backbone of countless developer tools, exposing repositories, commits, pull requests, issues, actions workflows and org data.",
    baseUrl: "https://api.github.com",
    docsUrl: "https://docs.github.com/en/rest",
    authType: "OAuth",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "github", "dev-tools"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "gitlab-api",
    name: "GitLab API",
    description: "Official GitLab REST & GraphQL APIs for projects, pipelines and issues.",
    longDescription:
      "GitLab's API covers project management, CI/CD pipelines, merge requests and container registries for the open-source DevOps platform.",
    baseUrl: "https://gitlab.com/api/v4",
    docsUrl: "https://docs.gitlab.com/ee/api/rest/",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["technology", "devops"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "npm-registry-api",
    name: "npm Registry API",
    description: "Public registry API for querying package metadata, versions and downloads.",
    longDescription:
      "npm's public registry API exposes package metadata, dependency trees, versions and weekly download stats for the entire JavaScript ecosystem.",
    baseUrl: "https://registry.npmjs.org",
    docsUrl: "https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "npm", "javascript"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "pypi-json-api",
    name: "PyPI JSON API",
    description: "Public metadata API for Python packages on the Python Package Index.",
    longDescription:
      "PyPI's JSON endpoint returns package metadata, release history and project URLs for any published Python package.",
    baseUrl: "https://pypi.org/pypi",
    docsUrl: "https://warehouse.pypa.io/api-reference/json.html",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "python"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "cloudflare-api",
    name: "Cloudflare API",
    description: "Official API for DNS, CDN, security and Workers management.",
    longDescription:
      "Cloudflare's REST API lets you programmatically manage DNS records, firewall rules, caching, Workers and Zero Trust configuration.",
    baseUrl: "https://api.cloudflare.com/client/v4",
    docsUrl: "https://developers.cloudflare.com/api/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["technology", "cdn", "dns"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "vercel-api",
    name: "Vercel REST API",
    description: "Official API to manage Vercel deployments, domains and projects.",
    longDescription:
      "Vercel's API lets teams automate deployments, environment variables, domains and edge configuration for frontend projects.",
    baseUrl: "https://api.vercel.com",
    docsUrl: "https://vercel.com/docs/rest-api",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["technology", "hosting", "deployment"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "netlify-api",
    name: "Netlify API",
    description: "Official API to manage Netlify sites, builds, forms and deploy hooks.",
    longDescription:
      "Netlify's open API enables automated site creation, deploy triggers, form submissions retrieval and DNS management.",
    baseUrl: "https://api.netlify.com/api/v1",
    docsUrl: "https://docs.netlify.com/api/get-started/",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["technology", "hosting", "jamstack"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "ipify",
    name: "ipify",
    description: "Dead-simple public IP address API — one call returns your IP.",
    longDescription:
      "ipify is a lightweight, free and open-source service that returns the caller's public IP address as JSON, text or JSONP.",
    baseUrl: "https://api.ipify.org",
    docsUrl: "https://www.ipify.org/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "networking"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "httpbin",
    name: "httpbin.org",
    description: "HTTP request & response testing service for debugging API clients.",
    longDescription:
      "httpbin is an open-source utility that echoes back request headers, methods, cookies and status codes — a favorite for testing HTTP client libraries.",
    baseUrl: "https://httpbin.org",
    docsUrl: "https://httpbin.org/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "testing", "debugging"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "jsonplaceholder",
    name: "JSONPlaceholder",
    description: "Free fake REST API for prototyping — posts, comments, users, todos.",
    longDescription:
      "JSONPlaceholder is the go-to free fake API used worldwide for frontend prototyping, offering CRUD-style endpoints without a real backend.",
    baseUrl: "https://jsonplaceholder.typicode.com",
    docsUrl: "https://jsonplaceholder.typicode.com/guide/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "prototyping"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "dnsjson",
    name: "DNS-over-HTTPS (Cloudflare / Google)",
    description: "Public resolver APIs to run DNS lookups over HTTPS from the browser.",
    longDescription:
      "Cloudflare (1.1.1.1) and Google (8.8.8.8) both expose free DNS-over-HTTPS JSON endpoints usable directly from client-side JavaScript.",
    baseUrl: "https://cloudflare-dns.com/dns-query",
    docsUrl: "https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "dns", "networking"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "letsencrypt-acme",
    name: "Let's Encrypt ACME API",
    description: "Free, automated, open certificate authority protocol for HTTPS.",
    longDescription:
      "Let's Encrypt's ACME protocol powers automatic, free SSL/TLS certificate issuance used by the majority of HTTPS sites on the web today.",
    baseUrl: "https://acme-v02.api.letsencrypt.org/directory",
    docsUrl: "https://letsencrypt.org/docs/",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["technology", "security", "ssl"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "docker-hub-api",
    name: "Docker Hub API",
    description: "Public API for browsing Docker image repositories and tags.",
    longDescription:
      "Docker Hub's API exposes public image repositories, tags, pull counts of images, and vulnerability scan summaries.",
    baseUrl: "https://hub.docker.com/v2",
    docsUrl: "https://docs.docker.com/reference/api/hub/latest/",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["technology", "docker", "containers"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "stackexchange-api",
    name: "Stack Exchange API",
    description: "Official API for Stack Overflow & the whole Stack Exchange network.",
    longDescription:
      "The Stack Exchange API grants read access to questions, answers, tags and user reputation across Stack Overflow and 170+ other communities.",
    baseUrl: "https://api.stackexchange.com/2.3",
    docsUrl: "https://api.stackexchange.com/docs",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "stackoverflow", "qa"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "dev-to-api",
    name: "DEV.to API",
    description: "Official API for the DEV Community — articles, tags and users.",
    longDescription:
      "The dev.to (Forem) API exposes published articles, comments, tags and user profile data from the popular developer blogging platform.",
    baseUrl: "https://dev.to/api",
    docsUrl: "https://developers.forem.com/api",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "blogging", "community"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "hacker-news-api",
    name: "Hacker News API",
    description: "Official Firebase-backed API for Hacker News stories, comments and users.",
    longDescription:
      "The official HN API (built on Firebase) exposes top/new/best story IDs, nested comment trees and user karma completely free with no key.",
    baseUrl: "https://hacker-news.firebaseio.com/v0",
    docsUrl: "https://github.com/HackerNews/API",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "news", "community"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "producthunt-api",
    name: "Product Hunt API",
    description: "Official GraphQL API for daily-launched products, votes and makers.",
    longDescription:
      "Product Hunt's GraphQL API exposes daily product launches, topics, votes and maker profiles for the startup discovery platform.",
    baseUrl: "https://api.producthunt.com/v2/api/graphql",
    docsUrl: "https://api.producthunt.com/v2/docs",
    authType: "OAuth",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["technology", "startups", "graphql"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "wappalyzer-lite",
    name: "Wappalyzer-style tech detection (open-source)",
    description: "Open-source signatures database to detect the technology stack behind any site.",
    longDescription:
      "Open-source technology fingerprinting projects (Wappalyzer's public dataset and its forks) let you identify a website's frameworks, CMS and analytics tools from response headers and HTML patterns.",
    baseUrl: "https://github.com/enthec/webappanalyzer",
    docsUrl: "https://github.com/enthec/webappanalyzer",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["technology", "fingerprinting", "open-source"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "whois-json",
    name: "WHOIS JSON API (RDAP)",
    description: "Free, standardized domain WHOIS/RDAP lookup API.",
    longDescription:
      "RDAP (the modern successor to WHOIS) is an IETF-standardized, free JSON protocol for domain and IP registration lookups, run by registries worldwide.",
    baseUrl: "https://rdap.org",
    docsUrl: "https://www.icann.org/rdap",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["technology", "domains", "networking"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "shields-io",
    name: "Shields.io Badges",
    description: "Generate live SVG status badges for build, version, license and more.",
    longDescription:
      "Shields.io is the open-source engine behind millions of README badges, dynamically rendering SVGs for build status, package versions and social stats.",
    baseUrl: "https://img.shields.io",
    docsUrl: "https://shields.io/",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["technology", "badges", "open-source"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
