import type { ApiEntry } from "./types";

export const weatherNatureApis: ApiEntry[] = [
  {
    slug: "open-meteo",
    name: "Open-Meteo",
    description: "Completely free, open-source weather forecast API with no key needed.",
    longDescription:
      "Open-Meteo is a fully open-source weather API offering hourly/daily forecasts, historical weather and air quality — free for non-commercial use with zero API key.",
    baseUrl: "https://api.open-meteo.com/v1",
    docsUrl: "https://open-meteo.com/en/docs",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["weather", "open-source"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "openweathermap",
    name: "OpenWeatherMap",
    description: "Popular free-tier weather API with current, forecast and historical data.",
    longDescription:
      "OpenWeatherMap is one of the most widely integrated weather APIs, offering current conditions, 5-day forecasts and historical weather with a free tier.",
    baseUrl: "https://api.openweathermap.org/data/2.5",
    docsUrl: "https://openweathermap.org/api",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["weather"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "weatherapi-com",
    name: "WeatherAPI.com",
    description: "Free-tier weather, astronomy and air-quality API.",
    longDescription:
      "WeatherAPI.com offers real-time weather, 14-day forecasts, astronomy (sunrise/moon phase) and air-quality data with a generous free plan.",
    baseUrl: "https://api.weatherapi.com/v1",
    docsUrl: "https://www.weatherapi.com/docs/",
    authType: "apiKey",
    https: true,
    cors: "Yes",
    isTestable: false,
    tags: ["weather", "astronomy"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "airvisual-api",
    name: "IQAir AirVisual API",
    description: "Global air-quality index API by city, state and country.",
    longDescription:
      "IQAir's AirVisual API returns real-time air-quality index (AQI), pollution levels and weather for cities worldwide.",
    baseUrl: "https://api.airvisual.com/v2",
    docsUrl: "https://www.iqair.com/dashboard/api",
    authType: "apiKey",
    https: true,
    cors: "Unknown",
    isTestable: false,
    tags: ["weather", "air-quality"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "usgs-water",
    name: "USGS Water Services API",
    description: "Official US river, lake and groundwater monitoring data feed.",
    longDescription:
      "The USGS Water Services API streams real-time river flow, water level and groundwater data collected from thousands of monitoring stations across the US.",
    baseUrl: "https://waterservices.usgs.gov/nwis",
    docsUrl: "https://waterservices.usgs.gov/docs/",
    authType: "No",
    https: true,
    cors: "Unknown",
    isTestable: true,
    tags: ["nature", "water", "environment"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "gbif-api",
    name: "GBIF Species Occurrence API",
    description: "Global biodiversity data — species occurrence records worldwide.",
    longDescription:
      "The Global Biodiversity Information Facility exposes hundreds of millions of free species-occurrence and taxonomy records for ecology research.",
    baseUrl: "https://api.gbif.org/v1",
    docsUrl: "https://www.gbif.org/developer/summary",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["nature", "biodiversity", "open-data"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
  {
    slug: "sunrise-sunset",
    name: "Sunrise-Sunset.org API",
    description: "Free API for sunrise, sunset and daylight-length calculations.",
    longDescription:
      "A simple, free API that returns sunrise, sunset, solar noon and day-length times for any latitude/longitude and date.",
    baseUrl: "https://api.sunrise-sunset.org",
    docsUrl: "https://sunrise-sunset.org/api",
    authType: "No",
    https: true,
    cors: "Yes",
    isTestable: true,
    tags: ["nature", "astronomy"],
    sourceListUrl: "https://github.com/public-apis/public-apis",
  },
];
